### ISSUE TITLE
Explore codecov.io for automated code coverage assessment

### ISSUE THREAD

**Issue by mattldawson** [NCAR/musica-core#5]
https://codecov.io/ is free for open-source projects and calculates the test coverage automatically. (see https://github.com/jacobwilliams/json-fortran for example)

**Comment by fvitt** [comment]
Sounds useful.  Are we open source?

**Comment by AndrewJConley** [comment]
I don't know how they pull this off.  There seem to be so many useful aspects of this: github actions, plots of changes in coverage, identifying sections of code without test coverage, indications of code/directories to ignore.  And they support all of our languages: python, fortran, javascript(maybe), PHP.  We are open source, but maybe not yet in the 2.0 fork.

**Comment by mattldawson** [comment]
music-box and musica-core are both public and include the Apache 2.0 license
